import Foundation
import WebKit
#if canImport(AppKit)
import AppKit
#endif

/// Generates PDFs from Invoice or Memo by rendering HTML via WKWebView.
@MainActor
final class PDFService {

    static let shared = PDFService()

    /// UserDefaults key for stored company logo image data (e.g. from file picker).
    static let companyLogoUserDefaultsKey = "companyLogoImageData"

    /// Company name used in the document header when no custom name is set.
    var companyName: String { "Quality Diajewels Inc." }

    private let letterWidth: CGFloat = 612
    private let letterHeight: CGFloat = 792

    /// Cached DateFormatter for medium-style dates (avoids per-call allocation).
    private let mediumDateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateStyle = .medium
        return f
    }()

    private init() {}

    // MARK: - Temp File Cleanup

    /// Removes document-*.pdf files in the temp directory older than 1 hour.
    static func cleanupStaleTempFiles() {
        let tempDir = FileManager.default.temporaryDirectory
        let fm = FileManager.default
        guard let contents = try? fm.contentsOfDirectory(
            at: tempDir, includingPropertiesForKeys: [.creationDateKey], options: .skipsHiddenFiles
        ) else { return }

        let oneHourAgo = Date().addingTimeInterval(-3600)
        for fileURL in contents {
            guard fileURL.lastPathComponent.hasPrefix("document-"),
                  fileURL.pathExtension == "pdf" else { continue }
            if let attrs = try? fm.attributesOfItem(atPath: fileURL.path),
               let creationDate = attrs[.creationDate] as? Date,
               creationDate < oneHourAgo {
                try? fm.removeItem(at: fileURL)
            }
        }
    }

    // MARK: - Public API

    func generatePDF(invoice: Invoice, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        Self.cleanupStaleTempFiles()
        let html = buildHTML(
            documentTitle: "INVOICE",
            companyName: companyName,
            customerAddress: formatAddress(invoice.customer),
            metaLines: invoiceMetaLines(invoice),
            lineItems: Array(invoice.lineItems),
            subtotal: invoiceSubtotal(invoice),
            tax: nil,
            grandTotal: invoiceTotal(invoice),
            notes: invoice.notes,
            logoBase64: loadLogoBase64()
        )
        renderHTMLToPDF(html: html, completion: completion)
    }

    func generatePDF(memo: Memo, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        Self.cleanupStaleTempFiles()
        let html = buildHTML(
            documentTitle: "MEMO",
            companyName: companyName,
            customerAddress: formatAddress(memo.customer),
            metaLines: memoMetaLines(memo),
            lineItems: Array(memo.lineItems),
            subtotal: memoSubtotal(memo),
            tax: nil,
            grandTotal: memoTotal(memo),
            notes: memo.notes,
            logoBase64: loadLogoBase64()
        )
        renderHTMLToPDF(html: html, completion: completion)
    }

    /// Removes a temporary PDF file previously generated by this service.
    func cleanupTempFile(at url: URL) {
        try? FileManager.default.removeItem(at: url)
    }

    // MARK: - Logo

    private func loadLogoBase64() -> String? {
        guard let data = UserDefaults.standard.data(forKey: Self.companyLogoUserDefaultsKey),
              !data.isEmpty else { return nil }
        return data.base64EncodedString()
    }

    /// Call from UI after user picks a logo image to store it for PDF generation.
    static func saveCompanyLogo(_ imageData: Data) {
        UserDefaults.standard.set(imageData, forKey: companyLogoUserDefaultsKey)
    }

    // MARK: - HTML Template

    private func buildHTML(
        documentTitle: String,
        companyName: String,
        customerAddress: String,
        metaLines: [String],
        lineItems: [LineItem],
        subtotal: Decimal,
        tax: Decimal?,
        grandTotal: Decimal,
        notes: String,
        logoBase64: String?
    ) -> String {
        let logoImg: String
        if let base64 = logoBase64 {
            logoImg = #"<img src="data:image/png;base64,\#(base64)" alt="Logo" class="logo" />"#
        } else {
            logoImg = ""
        }

        let metaBlock = metaLines.map { "<p class=\"meta-line\">\($0)</p>" }.joined(separator: "\n")
        let rows = lineItems.map { item in
            """
            <tr>
                <td>\(escape(item.displaySku))</td>
                <td>\(escape(item.displayName))</td>
                <td class="num">\(escape(item.displayCarats))</td>
                <td class="num">\(escape(item.rate.asCurrency))</td>
                <td class="num">\(escape(item.amount.asCurrency))</td>
            </tr>
            """
        }.joined(separator: "\n")

        let taxRow: String
        if let t = tax, t > 0 {
            taxRow = "<tr><td colspan=\"4\" class=\"label\">Tax</td><td class=\"num\">\(t.asCurrency)</td></tr>"
        } else {
            taxRow = ""
        }

        let notesBlock: String
        if !notes.isEmpty {
            notesBlock = """
            <div class="notes">
                <strong>Notes</strong><br/>
                \(escape(notes))
            </div>
            """
        } else {
            notesBlock = ""
        }

        // Read company info from UserDefaults, falling back to parameter
        let storedCompanyName = UserDefaults.standard.string(forKey: "companyName")
        let displayCompanyName = (storedCompanyName?.isEmpty == false) ? storedCompanyName! : companyName
        let companyAddress = UserDefaults.standard.string(forKey: "companyAddress") ?? ""
        let companyPhone = UserDefaults.standard.string(forKey: "companyPhone") ?? ""
        let companyEmail = UserDefaults.standard.string(forKey: "companyEmail") ?? ""

        var companyInfoLines: [String] = [escape(displayCompanyName)]
        if !companyAddress.isEmpty { companyInfoLines.append(contentsOf: companyAddress.components(separatedBy: "\n").map { escape($0) }) }
        if !companyPhone.isEmpty { companyInfoLines.append(escape(companyPhone)) }
        if !companyEmail.isEmpty { companyInfoLines.append(escape(companyEmail)) }
        let companyBlock = companyInfoLines.joined(separator: "<br/>")

        return """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                @page {
                    margin: 18mm 15mm 22mm 15mm;
                    @bottom-center {
                        content: counter(page) " of " counter(pages);
                        font-size: 9pt;
                        color: #888;
                    }
                }
                * { box-sizing: border-box; margin: 0; padding: 0; }
                body {
                    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                    font-size: 10pt;
                    color: #1a1a1a;
                    background: #fff;
                    padding: 0;
                    line-height: 1.5;
                }
                h1, h2, h3 { font-family: Georgia, 'Times New Roman', Times, serif; }

                /* Header */
                .header {
                    display: flex;
                    justify-content: space-between;
                    align-items: flex-start;
                    padding-bottom: 16px;
                    border-bottom: 2px solid #1a1a1a;
                    margin-bottom: 20px;
                }
                .logo { max-height: 60px; max-width: 180px; }
                .company-info {
                    text-align: right;
                    font-size: 9pt;
                    color: #444;
                    line-height: 1.6;
                }
                .company-info strong {
                    font-size: 13pt;
                    color: #1a1a1a;
                    display: block;
                    margin-bottom: 2px;
                }

                /* Document Title */
                .doc-title {
                    font-size: 24pt;
                    font-weight: 700;
                    letter-spacing: 2px;
                    color: #1a1a1a;
                    margin: 20px 0 6px 0;
                    text-transform: uppercase;
                }

                /* Meta & Bill-To Row */
                .info-row {
                    display: flex;
                    justify-content: space-between;
                    margin: 12px 0 24px 0;
                }
                .bill-to, .meta {
                    width: 48%;
                }
                .section-label {
                    font-size: 8pt;
                    text-transform: uppercase;
                    letter-spacing: 1.5px;
                    color: #888;
                    font-weight: 600;
                    margin-bottom: 4px;
                }
                .meta-line {
                    margin: 1px 0;
                    color: #333;
                    font-size: 10pt;
                }

                /* Line Items Table */
                .items-table {
                    width: 100%;
                    border-collapse: collapse;
                    margin: 0 0 16px 0;
                }
                .items-table thead th {
                    background: #f5f5f5;
                    border-bottom: 2px solid #1a1a1a;
                    border-top: 2px solid #1a1a1a;
                    padding: 8px 10px;
                    text-align: left;
                    font-size: 8pt;
                    text-transform: uppercase;
                    letter-spacing: 1px;
                    color: #555;
                    font-weight: 600;
                }
                .items-table thead { display: table-header-group; }
                .items-table tbody tr { page-break-inside: avoid; }
                .items-table tbody tr:nth-child(even) { background: #fafafa; }
                .items-table tbody td {
                    padding: 7px 10px;
                    border-bottom: 1px solid #e5e5e5;
                    font-size: 10pt;
                    vertical-align: top;
                }
                .items-table td.num { text-align: right; font-variant-numeric: tabular-nums; }

                /* Totals */
                .totals-wrapper {
                    display: flex;
                    justify-content: flex-end;
                    margin-top: 8px;
                }
                .totals-table {
                    width: 260px;
                    border-collapse: collapse;
                }
                .totals-table td {
                    padding: 5px 10px;
                    font-size: 10pt;
                }
                .totals-table .label { text-align: right; color: #555; }
                .totals-table .num { text-align: right; font-weight: 500; font-variant-numeric: tabular-nums; }
                .totals-table .grand td {
                    border-top: 2px solid #1a1a1a;
                    font-size: 13pt;
                    font-weight: 700;
                    padding-top: 8px;
                    color: #1a1a1a;
                }

                /* Notes */
                .notes {
                    margin-top: 28px;
                    padding: 12px 14px;
                    background: #f8f8f8;
                    border-left: 3px solid #ccc;
                    border-radius: 2px;
                    font-size: 9pt;
                    color: #555;
                    line-height: 1.6;
                }
                .notes strong { color: #333; }

                /* Footer */
                .footer {
                    position: fixed;
                    bottom: 0;
                    left: 0;
                    right: 0;
                    text-align: center;
                    font-size: 8pt;
                    color: #aaa;
                    padding: 8px 0;
                    border-top: 1px solid #e5e5e5;
                }

                @media print {
                    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div>\(logoImg)</div>
                <div class="company-info">\(companyBlock)</div>
            </div>

            <h1 class="doc-title">\(escape(documentTitle))</h1>

            <div class="info-row">
                <div class="bill-to">
                    <div class="section-label">Bill To</div>
                    \(customerAddress.isEmpty ? "<p>—</p>" : "<p>\(customerAddress)</p>")
                </div>
                <div class="meta">
                    <div class="section-label">Details</div>
                    \(metaBlock)
                </div>
            </div>

            <table class="items-table">
                <thead>
                    <tr>
                        <th>SKU</th>
                        <th>Description</th>
                        <th style="text-align:right">Carats</th>
                        <th style="text-align:right">Rate</th>
                        <th style="text-align:right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    \(rows)
                </tbody>
            </table>

            <div class="totals-wrapper">
                <table class="totals-table">
                    <tr><td class="label">Subtotal</td><td class="num">\(subtotal.asCurrency)</td></tr>
                    \(taxRow)
                    <tr class="grand"><td class="label">Total</td><td class="num">\(grandTotal.asCurrency)</td></tr>
                </table>
            </div>

            \(notesBlock)

            <div class="footer">
                \(escape(displayCompanyName)) &middot; Thank you for your business
            </div>

            <script>
                // Page numbers via JavaScript (for WKWebView rendering)
                (function() {
                    var footer = document.querySelector('.footer');
                    if (footer) footer.innerHTML += '';
                })();
            </script>
        </body>
        </html>
        """
    }

    private func escape(_ s: String) -> String {
        s
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private func formatAddress(_ customer: Customer?) -> String {
        guard let c = customer else { return "" }
        var parts: [String] = []
        let name = c.displayName
        if !name.isEmpty { parts.append(name) }
        if !c.company.isEmpty { parts.append(c.company) }
        if !c.address.isEmpty { parts.append(c.address) }
        let cityZip = [c.city, c.zip].filter { !$0.isEmpty }
        if !cityZip.isEmpty { parts.append(cityZip.joined(separator: " ")) }
        if !c.country.isEmpty { parts.append(c.country) }
        return parts.joined(separator: "<br/>")
    }

    private func invoiceMetaLines(_ invoice: Invoice) -> [String] {
        var lines: [String] = []
        if !invoice.referenceNumber.isEmpty { lines.append("Invoice #\(invoice.referenceNumber)") }
        lines.append("Date: \(formatDate(invoice.invoiceDate))")
        if let due = invoice.dueDate { lines.append("Due: \(formatDate(due))") }
        if !invoice.terms.isEmpty { lines.append("Terms: \(invoice.terms)") }
        return lines
    }

    private func memoMetaLines(_ memo: Memo) -> [String] {
        var lines: [String] = []
        if !memo.referenceNumber.isEmpty { lines.append("Memo #\(memo.referenceNumber)") }
        if let date = memo.dateAssigned { lines.append("Date: \(formatDate(date))") }
        lines.append("Status: \(memo.status.rawValue)")
        return lines
    }

    private func formatDate(_ date: Date) -> String {
        mediumDateFormatter.string(from: date)
    }

    private func invoiceSubtotal(_ invoice: Invoice) -> Decimal {
        invoice.lineItems.reduce(0) { $0 + $1.amount }
    }

    private func invoiceTotal(_ invoice: Invoice) -> Decimal {
        invoiceSubtotal(invoice)
    }

    private func memoSubtotal(_ memo: Memo) -> Decimal {
        memo.lineItems.reduce(0) { $0 + $1.amount }
    }

    private func memoTotal(_ memo: Memo) -> Decimal {
        memoSubtotal(memo)
    }

    // MARK: - Render HTML to PDF

    private func renderHTMLToPDF(html: String, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        let runner = PDFWebViewRunner(
            html: html,
            pageSize: CGSize(width: letterWidth, height: letterHeight)
        ) { result in
            completion(result)
        }
        runner.run()
    }
}

// MARK: - WKWebView PDF runner (must run on main, retains itself until done)

private final class PDFWebViewRunner: NSObject, WKNavigationDelegate {
    let html: String
    let pageSize: CGSize
    let completion: (Result<URL, Error>) -> Void
    private var webView: WKWebView?
    private var selfRetain: PDFWebViewRunner?
    private var timeoutWorkItem: DispatchWorkItem?
    private var didComplete: Bool = false

    enum PDFError: LocalizedError {
        case timeout
        var errorDescription: String? {
            switch self {
            case .timeout: return "PDF generation timed out after 30 seconds"
            }
        }
    }

    init(html: String, pageSize: CGSize, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        self.html = html
        self.pageSize = pageSize
        self.completion = completion
        super.init()
    }

    func run() {
        let config = WKWebViewConfiguration()
        let wv = WKWebView(frame: CGRect(origin: .zero, size: pageSize), configuration: config)
        wv.navigationDelegate = self
        webView = wv
        selfRetain = self
        wv.loadHTMLString(html, baseURL: nil)

        // 30-second timeout
        let timeout = DispatchWorkItem { [weak self] in
            guard let self = self, !self.didComplete else { return }
            self.didComplete = true
            self.webView = nil
            self.selfRetain = nil
            self.completion(.failure(PDFError.timeout))
        }
        timeoutWorkItem = timeout
        DispatchQueue.main.asyncAfter(deadline: .now() + 30, execute: timeout)
    }

    private func finish(with result: Result<URL, Error>) {
        guard !didComplete else { return }
        didComplete = true
        timeoutWorkItem?.cancel()
        webView = nil
        selfRetain = nil
        completion(result)
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        let config = WKPDFConfiguration()
        config.rect = CGRect(origin: .zero, size: pageSize)
        webView.createPDF(configuration: config) { [weak self] result in
            guard let self = self else { return }
            switch result {
            case .success(let data):
                do {
                    let fileName = "document-\(UUID().uuidString).pdf"
                    let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
                    try data.write(to: url)
                    self.finish(with: .success(url))
                } catch {
                    self.finish(with: .failure(error))
                }
            case .failure(let error):
                self.finish(with: .failure(error))
            }
        }
    }

    func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
        finish(with: .failure(error))
    }
}
