import Foundation
import WebKit
#if canImport(AppKit)
import AppKit
#endif

/// Generates PDFs from Invoice or Memo by rendering HTML via WKWebView.
@MainActor
final class PDFService {

    static let shared = PDFService()

    /// UserDefaults key for stored company logo image data (e.g. from file picker).
    static let companyLogoUserDefaultsKey = "companyLogoImageData"

    /// Company name used in the document header when no custom name is set.
    var companyName: String { "Quality Diajewels Inc." }

    private let letterWidth: CGFloat = 612
    private let letterHeight: CGFloat = 792

    /// Cached DateFormatter for medium-style dates (avoids per-call allocation).
    private let mediumDateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateStyle = .medium
        return f
    }()

    private init() {}

    // MARK: - Temp File Cleanup

    /// Removes document-*.pdf files in the temp directory older than 1 hour.
    static func cleanupStaleTempFiles() {
        let tempDir = FileManager.default.temporaryDirectory
        let fm = FileManager.default
        guard let contents = try? fm.contentsOfDirectory(
            at: tempDir, includingPropertiesForKeys: [.creationDateKey], options: .skipsHiddenFiles
        ) else { return }

        let oneHourAgo = Date().addingTimeInterval(-3600)
        for fileURL in contents {
            guard fileURL.lastPathComponent.hasPrefix("document-"),
                  fileURL.pathExtension == "pdf" else { continue }
            if let attrs = try? fm.attributesOfItem(atPath: fileURL.path),
               let creationDate = attrs[.creationDate] as? Date,
               creationDate < oneHourAgo {
                try? fm.removeItem(at: fileURL)
            }
        }
    }

    // MARK: - Public API

    func generatePDF(invoice: Invoice, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        Self.cleanupStaleTempFiles()
        let html = buildHTML(
            documentTitle: "INVOICE",
            companyName: companyName,
            customerAddress: formatAddress(invoice.customer),
            metaLines: invoiceMetaLines(invoice),
            lineItems: Array(invoice.lineItems),
            subtotal: invoiceSubtotal(invoice),
            tax: nil,
            grandTotal: invoiceTotal(invoice),
            notes: invoice.notes,
            logoBase64: loadLogoBase64()
        )
        renderHTMLToPDF(html: html, completion: completion)
    }

    func generatePDF(memo: Memo, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        Self.cleanupStaleTempFiles()
        let html = buildHTML(
            documentTitle: "MEMO",
            companyName: companyName,
            customerAddress: formatAddress(memo.customer),
            metaLines: memoMetaLines(memo),
            lineItems: Array(memo.lineItems),
            subtotal: memoSubtotal(memo),
            tax: nil,
            grandTotal: memoTotal(memo),
            notes: memo.notes,
            logoBase64: loadLogoBase64()
        )
        renderHTMLToPDF(html: html, completion: completion)
    }

    /// Removes a temporary PDF file previously generated by this service.
    func cleanupTempFile(at url: URL) {
        try? FileManager.default.removeItem(at: url)
    }

    // MARK: - Logo

    private func loadLogoBase64() -> String? {
        guard let data = UserDefaults.standard.data(forKey: Self.companyLogoUserDefaultsKey),
              !data.isEmpty else { return nil }
        return data.base64EncodedString()
    }

    /// Call from UI after user picks a logo image to store it for PDF generation.
    static func saveCompanyLogo(_ imageData: Data) {
        UserDefaults.standard.set(imageData, forKey: companyLogoUserDefaultsKey)
    }

    // MARK: - HTML Template

    private func buildHTML(
        documentTitle: String,
        companyName: String,
        customerAddress: String,
        metaLines: [String],
        lineItems: [LineItem],
        subtotal: Decimal,
        tax: Decimal?,
        grandTotal: Decimal,
        notes: String,
        logoBase64: String?
    ) -> String {
        let logoImg: String
        if let base64 = logoBase64 {
            logoImg = #"<img src="data:image/png;base64,\#(base64)" alt="Logo" class="logo" />"#
        } else {
            logoImg = ""
        }

        let metaBlock = metaLines.map { "<p class=\"meta-line\">\($0)</p>" }.joined(separator: "\n")
        let rows = lineItems.map { item in
            """
            <tr>
                <td>\(escape(item.displaySku))</td>
                <td>\(escape(item.displayName))</td>
                <td class="num">\(escape(item.displayCarats))</td>
                <td class="num">\(escape(item.rate.asCurrency))</td>
                <td class="num">\(escape(item.amount.asCurrency))</td>
            </tr>
            """
        }.joined(separator: "\n")

        let taxRow: String
        if let t = tax, t > 0 {
            taxRow = "<tr><td colspan=\"4\" class=\"label\">Tax</td><td class=\"num\">\(t.asCurrency)</td></tr>"
        } else {
            taxRow = ""
        }

        let notesBlock: String
        if !notes.isEmpty {
            notesBlock = """
            <div class="notes">
                <strong>Notes</strong><br/>
                \(escape(notes))
            </div>
            """
        } else {
            notesBlock = ""
        }

        return """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                @page { margin: 20mm; }
                * { box-sizing: border-box; }
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 11pt; color: #000; background: #fff; margin: 0; padding: 24px; }
                tr { page-break-inside: avoid; }
                .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; }
                .logo { max-height: 56px; max-width: 180px; }
                .company { text-align: right; color: #333; }
                .doc-title { font-size: 22pt; font-weight: 700; margin: 16px 0; }
                .bill-to { margin: 16px 0; }
                .bill-to strong { display: block; margin-bottom: 4px; }
                .meta-line { margin: 2px 0; color: #444; }
                table { width: 100%; border-collapse: collapse; margin: 16px 0; }
                th, td { border: 1px solid #000; padding: 8px 10px; text-align: left; }
                th { background: #f0f0f0; font-weight: 600; }
                td.num { text-align: right; }
                .totals { margin-left: auto; width: 240px; margin-top: 8px; }
                .totals tr { border: none; }
                .totals td { border: none; border-top: 1px solid #000; padding: 4px 8px; }
                .totals .label { text-align: right; }
                .totals .num { text-align: right; font-weight: 600; }
                .notes { margin-top: 20px; padding: 10px; background: #f8f8f8; border-radius: 4px; }
                @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
            </style>
        </head>
        <body>
            <div class="header">
                <div>\(logoImg)</div>
                <div class="company">\(escape(companyName))</div>
            </div>
            <h1 class="doc-title">\(escape(documentTitle))</h1>
            <div class="meta">\(metaBlock)</div>
            <div class="bill-to">
                <strong>Bill To</strong>
                \(customerAddress.isEmpty ? "<p>—</p>" : "<p>\(escape(customerAddress))</p>")
            </div>
            <table>
                <thead>
                    <tr>
                        <th>SKU</th>
                        <th>Description</th>
                        <th>Carats</th>
                        <th>Rate</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    \(rows)
                </tbody>
            </table>
            <table class="totals">
                <tr><td class="label">Subtotal</td><td class="num">\(subtotal.asCurrency)</td></tr>
                \(taxRow)
                <tr><td class="label">Total</td><td class="num">\(grandTotal.asCurrency)</td></tr>
            </table>
            \(notesBlock)
        </body>
        </html>
        """
    }

    private func escape(_ s: String) -> String {
        s
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private func formatAddress(_ customer: Customer?) -> String {
        guard let c = customer else { return "" }
        var parts: [String] = []
        let name = c.displayName
        if !name.isEmpty { parts.append(name) }
        if !c.company.isEmpty { parts.append(c.company) }
        if !c.address.isEmpty { parts.append(c.address) }
        let cityZip = [c.city, c.zip].filter { !$0.isEmpty }
        if !cityZip.isEmpty { parts.append(cityZip.joined(separator: " ")) }
        if !c.country.isEmpty { parts.append(c.country) }
        return parts.joined(separator: "<br/>")
    }

    private func invoiceMetaLines(_ invoice: Invoice) -> [String] {
        var lines: [String] = []
        if !invoice.referenceNumber.isEmpty { lines.append("Invoice #\(invoice.referenceNumber)") }
        lines.append("Date: \(formatDate(invoice.invoiceDate))")
        if let due = invoice.dueDate { lines.append("Due: \(formatDate(due))") }
        if !invoice.terms.isEmpty { lines.append("Terms: \(invoice.terms)") }
        return lines
    }

    private func memoMetaLines(_ memo: Memo) -> [String] {
        var lines: [String] = []
        if !memo.referenceNumber.isEmpty { lines.append("Memo #\(memo.referenceNumber)") }
        if let date = memo.dateAssigned { lines.append("Date: \(formatDate(date))") }
        lines.append("Status: \(memo.status.rawValue)")
        return lines
    }

    private func formatDate(_ date: Date) -> String {
        mediumDateFormatter.string(from: date)
    }

    private func invoiceSubtotal(_ invoice: Invoice) -> Decimal {
        invoice.lineItems.reduce(0) { $0 + $1.amount }
    }

    private func invoiceTotal(_ invoice: Invoice) -> Decimal {
        invoiceSubtotal(invoice)
    }

    private func memoSubtotal(_ memo: Memo) -> Decimal {
        memo.lineItems.reduce(0) { $0 + $1.amount }
    }

    private func memoTotal(_ memo: Memo) -> Decimal {
        memoSubtotal(memo)
    }

    // MARK: - Render HTML to PDF

    private func renderHTMLToPDF(html: String, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        let runner = PDFWebViewRunner(
            html: html,
            pageSize: CGSize(width: letterWidth, height: letterHeight)
        ) { result in
            completion(result)
        }
        runner.run()
    }
}

// MARK: - WKWebView PDF runner (must run on main, retains itself until done)

private final class PDFWebViewRunner: NSObject, WKNavigationDelegate {
    let html: String
    let pageSize: CGSize
    let completion: (Result<URL, Error>) -> Void
    private var webView: WKWebView?
    private var selfRetain: PDFWebViewRunner?
    private var timeoutWorkItem: DispatchWorkItem?
    private var didComplete: Bool = false

    enum PDFError: LocalizedError {
        case timeout
        var errorDescription: String? {
            switch self {
            case .timeout: return "PDF generation timed out after 30 seconds"
            }
        }
    }

    init(html: String, pageSize: CGSize, completion: @escaping @Sendable (Result<URL, Error>) -> Void) {
        self.html = html
        self.pageSize = pageSize
        self.completion = completion
        super.init()
    }

    func run() {
        let config = WKWebViewConfiguration()
        let wv = WKWebView(frame: CGRect(origin: .zero, size: pageSize), configuration: config)
        wv.navigationDelegate = self
        webView = wv
        selfRetain = self
        wv.loadHTMLString(html, baseURL: nil)

        // 30-second timeout
        let timeout = DispatchWorkItem { [weak self] in
            guard let self = self, !self.didComplete else { return }
            self.didComplete = true
            self.webView = nil
            self.selfRetain = nil
            self.completion(.failure(PDFError.timeout))
        }
        timeoutWorkItem = timeout
        DispatchQueue.main.asyncAfter(deadline: .now() + 30, execute: timeout)
    }

    private func finish(with result: Result<URL, Error>) {
        guard !didComplete else { return }
        didComplete = true
        timeoutWorkItem?.cancel()
        webView = nil
        selfRetain = nil
        completion(result)
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        let config = WKPDFConfiguration()
        config.rect = CGRect(origin: .zero, size: pageSize)
        webView.createPDF(configuration: config) { [weak self] result in
            guard let self = self else { return }
            switch result {
            case .success(let data):
                do {
                    let fileName = "document-\(UUID().uuidString).pdf"
                    let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
                    try data.write(to: url)
                    self.finish(with: .success(url))
                } catch {
                    self.finish(with: .failure(error))
                }
            case .failure(let error):
                self.finish(with: .failure(error))
            }
        }
    }

    func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
        finish(with: .failure(error))
    }
}
